### PR TITLE
HLS mainly uses MPEG2TS container.

### PR DESCRIPTION
**Pull request by nevil**
HLS mainly uses the MPEG2 Transport Stream container.

### CODE REVIEW

**Comment by chriseidhof** [comment]
Ping @fkuehne @carolanitz =)

**Comment by fkuehne** [comment]
This is indeed incorrect and should read "HLS typically consists of small chunks of H.264/AAC video stored in the MPEG-TS container format” with a link to http://en.wikipedia.org/wiki/MPEG_transport_stream

Thanks!

**Comment by nevil** [comment]
Nitpicking, but I used "MPEG-2 Transport Stream" to be consistent with the HLS RFC.
But any change is better than MP4 :-)

Should I update the Pull Request, or you will handle it?
Thanks

**Comment by fkuehne** [comment]
Actually there is only MPEG-TS which is part of the MPEG2 standard (see the Wikipedia article). Prior to v2, there was no TS and it is basically unchanged since then.

Natalye just merged the sentence I posted here along with the Wikipedia link. It will appear on the website shortly.

Thanks for spotting!

**Pull request closed without merging**
