### PR TITLE
Update 2015-01-13-andy-matuschak.md

### PR DESCRIPTION
**Pull request by RuiAAPeres**

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
The only thing I changed was "along many axes" to "along many axis"

**Comment by chriseidhof** [comment]
Ah, I think this pull request is mistaken: I think axes is the plural of axis. Ping @deutschbitte to make sure that I don't accidentally close it!

**Comment by deutschbitte** [comment]
@chriseidhof Yeah, "axes" is correct, not "axis." The original was fine.

**Comment by chriseidhof** [comment]
Thanks! @RuiAAPeres, thanks for helping out though!

**Pull request closed without merging**
